---

- name: install docker-ce for RedHat
  when: ansible_os_family == "RedHat"
  yum: 
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
        state: latest
        update_cache: 1

- name: install python dependencies for RedHat
  when: ansible_os_family == "RedHat"
  yum:
        name: ['python3-pip', 'python3-setuptools', 'virtualenv']
        state: latest
        update_cache: 1

- name: install Docker for Debian
  when: ansible_os_family == 'Debian'
  apt: 
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
        state: latest
        update_cache: 1

- name: install python dependencies for Debian
  when: ansible_os_family == "Debian"
  apt:
    name: ["python3-pip", "python3-setuptools", "virtualenv"]
    state: latest
    update_cache: 1

- name: install 'Docker SDK for Python'
  pip:
        name: docker

- name: Start Docker
  service:
      name: docker
      state: started

- name: install 'Docker SDK for Python'
  pip:
        name: docker
